# Generated by Django 3.2.6 on 2021-08-26 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', models.BooleanField(default=True)),
                ('common_name', models.CharField(max_length=50)),
                ('genus', models.CharField(max_length=30)),
                ('species', models.CharField(max_length=30)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('nickname', models.CharField(max_length=30, null=True)),
                ('area', models.IntegerField()),
                ('planted_date', models.DateField(default=datetime.date.today)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1)),
                ('state', models.CharField(choices=[('H', 'Healthy'), ('W', 'Worrying'), ('C', 'Critical')], default='H', max_length=1)),
                ('forest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='forest.forest')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'Infestation'), ('D', 'Damage'), ('A', 'Care'), ('C', 'Cutting'), ('F', 'Felling')], max_length=1)),
                ('details', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('tree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='forest.tree')),
            ],
        ),
    ]
