# Generated by Django 3.2.6 on 2021-08-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='area',
            new_name='area_nb',
        ),
        migrations.AlterField(
            model_name='tree',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
