# Generated by Django 3.2.6 on 2021-08-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='area_nb',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='planted_date',
        ),
        migrations.AddField(
            model_name='tree',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tree',
            name='species',
            field=models.CharField(choices=[('S', 'Spruce'), ('P', 'Pine'), ('B', 'Beech'), ('O', 'Oak'), ('F', 'Fir'), ('L', 'Larch'), ('A', 'Ash'), ('D', 'Alder'), ('M', 'Maple')], max_length=1),
        ),
    ]
