# Generated by Django 3.2.6 on 2021-09-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0002_auto_20210827_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='tree',
            name='species',
            field=models.CharField(choices=[('Spruce', 'Spruce'), ('Pine', 'Pine'), ('Beech', 'Beech'), ('Oak', 'Oak'), ('Fir', 'Fir'), ('Larch', 'Larch'), ('Ash', 'Ash'), ('Alder', 'Alder'), ('Maple', 'Maple')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tree',
            name='state',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Worrying', 'Worrying'), ('Critical', 'Critical')], default='H', max_length=20),
        ),
    ]
